apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: trading
spec:
  selector:
    app: redis-mq
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-mq
  namespace: trading
spec:
  selector:
    matchLabels:
      app: redis-mq
  serviceName: redis-service
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-mq
    spec:
      containers:
        - name: redis-mq
          image: redis